import 'package:wastewise/components/goods.dart';

class Mart {
  final List<Goods> goods = [
    Goods(
      name: 'Apple',
      description: 'Fresh and juicy',
      category: 'food',
      image: 'assets/images/apple.jpg',
      price: '1.99',
      expiredDate: '3 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Banana',
      description: 'Fresh and ripe',
      category: 'food',
      image: 'assets/images/banana.jpg',
      price: '0.99',
      expiredDate: '2 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Orange',
      description: 'Fresh and juicy',
      category: 'food',
      image: 'assets/images/orange.jpg',
      price: '1.49',
      expiredDate: '4 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Milk',
      description: 'Fresh and creamy',
      category: 'beverages',
      image: 'assets/images/milk.jpg',
      price: '2.99',
      expiredDate: '3 days left',
      quantity: '10',
    ),
    Goods(
      name: 'HausBoom',
      description: 'Cold and refreshing',
      category: 'beverages',
      image: 'assets/images/coke.jpg',
      price: '1.99',
      expiredDate: '2 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Vico',
      description: 'Cold and refreshing',
      category: 'beverages',
      image: 'assets/images/pepsi.jpg',
      price: '1.99',
      expiredDate: '2 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Shampoo',
      description: 'For shiny hair',
      category: 'health_beauty',
      image: 'assets/images/shampoo.jpg',
      price: '3.99',
      expiredDate: '5 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Soap',
      description: 'For clean hands',
      category: 'health_beauty',
      image: 'assets/images/soap.jpg',
      price: '1.99',
      expiredDate: '2 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Toothpaste',
      description: 'For fresh breath',
      category: 'health_beauty',
      image: 'assets/images/toothpaste.jpg',
      price: '2.99',
      expiredDate: '3 days left',
      quantity: '10',
    ),
    Goods(
      name: 'Paracetamol',
      description: 'For headaches',
      category: 'medicines',
      image: 'assets/images/paracetamol.jpg',
      price: '4.99',
      expiredDate: '7 days left',
      quantity: '2',
    )
  ];
}
